### ISSUE TITLE
Feature request: consider queries containing both compare with and facet

### ISSUE THREAD

**Issue by SalmaMrabetRiverty** [newrelic-experimental/talisker#6]
[NOTE]: # ( ^^ Provide a general summary of the request in the title above. ^^ )

## Summary

[NOTE]: # ( Provide a brief overview of what the new feature is all about. )

## Desired Behavior

[NOTE]: # ( Tell us how the new feature should work. Be specific. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Possible Solution

[NOTE]: # ( Not required. Suggest how to implement the addition or change. )

## Additional context

[TIP]:  # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by jsbnr** [comment]
Looking into this. "non-faceted compare with" is already supported.

**Comment by jsbnr** [comment]
This feature has been added in PR #8

**Comment by SalmaMrabetRiverty** [comment]
I have tested the code and found it to be working for all query types. The results were as expected.

Thank you for your prompt response !

**Comment by jsbnr** [comment]
Feature added in #8
