### ISSUE TITLE
NewRelic synthetic monitor with Terraform

### ISSUE THREAD

**Issue by EightyFifth** [newrelic-experimental/talisker#9]
Hi guys,

I am struggling with declaration of the resource "newrelic_synthetics_script_monitor" with "SCRIPT_API" type. There is an argument "script" within the resource. 

For script I have 2 data sources:
•	script itself - script.js
•	module template - header.tmpl 

Now the question is how should I describe "script" argument within "newrelic_synthetics_script_monitor" resource utilizing these 2 data sources?

Below is the example. My question is at the place with question marks
 
Example:

`//Script monitor
resource "newrelic_synthetics_script_monitor" "monitor" {
    name = var.monitorName
    type = "SCRIPT_API"
    period = var.frequency
    status = "ENABLED"
    location_private {
      guid         = data.newrelic_synthetics_private_location.location.id
      vse_password = "XXXXX" //Private location password
    }
    
    script = ??????????????
}

//script file data source
data "local_file" "base_js" {
    filename = "${path.module}/src/base_script.js"
}

//template file data source
data "template_file" "header_js" {
    template = templatefile(
               "${path.module}/src/script_header.tmpl",
               {
                 tasks = <<TASKBLOCK
[%{ for task in var.tasks ~}
{
    "id":${jsonencode(task.id)},
    "name":${jsonencode(task.name)},
    "accountId":${jsonencode(task.accountId)},
    "selector":${jsonencode(task.selector)},
    "chaining":${jsonencode(task.chaining)},
    "nullValue":${jsonencode(task.fillNullValue)},
    "invertResult":${jsonencode(task.invertResult)},
    "ingestType":${jsonencode(task.ingestType)},
    "query":${jsonencode(task.query)}
},
%{ endfor ~}]
TASKBLOCK
                monitorName = var.monitorName
                monitorId = newrelic_synthetics_script_monitor.monitor.id
                nameSpace = var.nameSpace
                insertKeyName = "TAL_INSERT_KEY"
                queryKeyName = "TAL_QUERY_KEY"
                keySuffix = replace(newrelic_synthetics_script_monitor.monitor.id,"-","_")
                dataCenter = var.dataCenter
                accountId = var.accountId
               }
        )
}`

Thank you in advance

Regards,
Sergii

**Comment by jsbnr** [comment]
I think you need the script attribute within the resource  like this:

script = "${data.template_file.header_js.rendered} ${data.local_file.base_js.content}"


I'll take a further look and bring the example up to date with the latest terraform resources soon.

**Comment by EightyFifth** [comment]
HI,
I will try suggested. Will reply once tested out.
Thanks a lot :)

**Comment by EightyFifth** [comment]
Hello,

I have tried suggested, however got the Cycle error:

`Error: Cycle: module.example1.data.template_file.header_js, module.example1.newrelic_synthetics_script_monitor.monitor`

**Comment by jsbnr** [comment]
Hey there. Ive reviewed this and yes, it seems the new resource changes the architecture of the script loading which, to cut a long story short, means the id of the resource is not available to the script. Ive refactored this and removed that dependency. Its a little more brittle but should be good. Ive tested this on latest provider and terraform versions.

See PR #10 

You should be good to go! Also rememebr you can deploy Talisker without terraform, just dorpping in the script into a monitor - some customers do just that, but wheres the fun in that?

**Comment by EightyFifth** [comment]
Hey,

Thanks for the reply. Without terraform all worked like a charm. I require modularity version control, that's why terraform :)
I'll try your changes.

Regards,
Sergei
